version: "3"
services:
    app:
        image: "application"
        build:
            context: .
            dockerfile: "Dockerfile"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - 8084:8082
    db:
        image: postgres:latest
        volumes:
            - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - ${DB_PORT}:5432
